export const initialAgenda = [
  {
    "ID": "1083",
    "Data Cadastro": "2026-09-17",
    "Data Atendimento": "2026-09-24",
    "Hora": "08:30",
    "Placa": "RXD8C18",
    "Loja": "OFICINA",
    "Modelo": "POLO TRACK MA",
    "Contato": "SESMA",
    "Local/Oficina": "OFICINA MECANICA ARRAIS",
    "Problemas Relatado": "REVISÃO DE 64.363",
    "Observação": "HERONDI",
    "Operador": "josiele sena alves",
    "O.S Externa": ""
  },
  {
    "ID": "1075",
    "Data Cadastro": "2026-09-16",
    "Data Atendimento": "2026-09-24",
    "Hora": "09:00",
    "Placa": "SZW7B25",
    "Loja": "OFICINA",
    "Modelo": "STRADA FREEDOM CABINE DUPLA",
    "Contato": "COHAB",
    "Local/Oficina": "OFICINA MECANICA ARRAIS",
    "Problemas Relatado": "REVISÃO DE 52.000 KM, ALINHAS ,BALANCEAR E VERIFICAR OS PNEUS E SUSPENSÃO",
    "Observação": "SUSANE",
    "Operador": "josiele sena alves",
    "O.S Externa": ""
  },
  {
    "ID": "1085",
    "Data Cadastro": "2026-09-18",
    "Data Atendimento": "2026-09-24",
    "Hora": "09:30",
    "Placa": "SZC4G23",
    "Loja": "OFICINA",
    "Modelo": "C3 LIVE",
    "Contato": "FASEPA",
    "Local/Oficina": "OFICINA MECANICA ARRAIS",
    "Problemas Relatado": "BARULHO FEIO  NA RODA DIANTEIRA DIRETA AO ANDAR",
    "Observação": "LAURO",
    "Operador": "josiele sena alves",
    "O.S Externa": ""
  },
  {
    "ID": "1089",
    "Data Cadastro": "2026-09-18",
    "Data Atendimento": "2026-09-24",
    "Hora": "10:00",
    "Placa": "TWT8I72",
    "Loja": "OFICINA",
    "Modelo": "RANGER XLS CABINE DUPLA DIESEL",
    "Contato": "PARAPAZ",
    "Local/Oficina": "FENIX AUTOMOVEIS LTDA (FORD)",
    "Problemas Relatado": "REVISÃO DE 16.000 KM, E VERIFICAR FREIOS",
    "Observação": "PAULO",
    "Operador": "josiele sena alves",
    "O.S Externa": ""
  },
  {
    "ID": "1091",
    "Data Cadastro": "2026-09-19",
    "Data Atendimento": "2026-09-24",
    "Hora": "10:00",
    "Placa": "SZB2F86",
    "Loja": "OFICINA",
    "Modelo": "TORO FREED T270",
    "Contato": "SEASTER",
    "Local/Oficina": "OFICINA MECANICA ARRAIS",
    "Problemas Relatado": "REVISÃO DE KM, SUSPENSÃO, TROCA DE PNEUS, SISTEMA DE FREIO",
    "Observação": "ALTAIR",
    "Operador": "josiele sena alves",
    "O.S Externa": ""
  },
  {
    "ID": "1078",
    "Data Cadastro": "2026-09-16",
    "Data Atendimento": "2026-09-23",
    "Hora": "08:00",
    "Placa": "SZM5G61",
    "Loja": "OFICINA",
    "Modelo": "OROCH PRO 1.6",
    "Contato": "FASEPA",
    "Local/Oficina": "OFICINA MECANICA ARRAIS",
    "Problemas Relatado": "REVISÃO DE KM",
    "Observação": "LAURO",
    "Operador": "josiele sena alves",
    "O.S Externa": ""
  },
  {
    "ID": "1063",
    "Data Cadastro": "2026-09-11",
    "Data Atendimento": "2026-09-23",
    "Hora": "08:30",
    "Placa": "TVP0J56",
    "Loja": "OFICINA",
    "Modelo": "C3 AIRCROSS FLPK7",
    "Contato": "SEASTER",
    "Local/Oficina": "PEUGEOT CITROEN DO BRASIL AUTOMOVEIS LTD",
    "Problemas Relatado": "REAGENDADO FAZER MANUTENÇÃO DE 20.000, TROCAR OS PNEUS E TROCAR O SUPORTE DO FAROL",
    "Observação": "ALTAIR",
    "Operador": "josiele sena alves",
    "O.S Externa": ""
  },
  {
    "ID": "1069",
    "Data Cadastro": "2026-09-15",
    "Data Atendimento": "2026-09-23",
    "Hora": "09:00",
    "Placa": "TWT8H52",
    "Loja": "OFICINA",
    "Modelo": "ONIX PLUS 10MT NB",
    "Contato": "SEASTER",
    "Local/Oficina": "RR CHEVROET ANANINDEUA",
    "Problemas Relatado": "REVISÃO 10.000 KM",
    "Observação": "ALTAIR",
    "Operador": "josiele sena alves",
    "O.S Externa": ""
  },
  {
    "ID": "1082",
    "Data Cadastro": "2026-09-17",
    "Data Atendimento": "2026-09-23",
    "Hora": "09:30",
    "Placa": "RWL8G39",
    "Loja": "OFICINA",
    "Modelo": "RANGER XLSCD4A32",
    "Contato": "ACARÁ - EDUCAÇÃO",
    "Local/Oficina": "OFICINA MECANICA ARRAIS",
    "Problemas Relatado": "FALHA NO FREIO, BAIXA DE OLEO, LUZ DA INJEÇÃO ACESA",
    "Observação": "RODRIGO",
    "Operador": "josiele sena alves",
    "O.S Externa": ""
  },
  {
    "ID": "1074",
    "Data Cadastro": "2026-09-16",
    "Data Atendimento": "2026-09-23",
    "Hora": "10:00",
    "Placa": "SZI4D27",
    "Loja": "OFICINA",
    "Modelo": "C3 - AIRCROSS FL 7",
    "Contato": "SESMA",
    "Local/Oficina": "PEUGEOT CITROEN DO BRASIL AUTOMOVEIS LTD",
    "Problemas Relatado": "REVISÃO DE 30.000 KM, SUSPENSÃO DIANTEIRA E VERIFICAR FREIOS",
    "Observação": "MAURO",
    "Operador": "josiele sena alves",
    "O.S Externa": ""
  },
  {
    "ID": "1079",
    "Data Cadastro": "2026-09-16",
    "Data Atendimento": "2026-09-22",
    "Hora": "08:00",
    "Placa": "SZD3A68",
    "Loja": "OFICINA",
    "Modelo": "SPIN  PREMIER 1.8",
    "Contato": "MELHOR EM CASA - SESMA",
    "Local/Oficina": "",
    "Problemas Relatado": "REVISÃO DE KM, SUSPENSÃO DIANTEIRA, VERIFICAR FREIOS, COMPLETAE O LIQUIDO DO ARREFERCIMENTO",
    "Observação": "",
    "Operador": "josiele sena alves",
    "O.S Externa": ""
  },
  {
    "ID": "1080",
    "Data Cadastro": "2026-09-16",
    "Data Atendimento": "2026-09-22",
    "Hora": "08:30",
    "Placa": "RWQ6J49",
    "Loja": "OFICINA",
    "Modelo": "RANGER XLSCD4A32",
    "Contato": "SEMEC",
    "Local/Oficina": "OFICINA MECANICA ARRAIS",
    "Problemas Relatado": "REVISÃO DE KM",
    "Observação": "SANTANA",
    "Operador": "josiele sena alves",
    "O.S Externa": ""
  },
  {
    "ID": "1071",
    "Data Cadastro": "2026-09-15",
    "Data Atendimento": "2026-09-22",
    "Hora": "09:00",
    "Placa": "RXD8C78",
    "Loja": "OFICINA",
    "Modelo": "POLO TRACK MA",
    "Contato": "SESMA",
    "Local/Oficina": "OFICINA MECANICA ARRAIS",
    "Problemas Relatado": "REVISÃO DE KM, TROCA DE PNEUS. E LAVAGEM",
    "Observação": "MAURO",
    "Operador": "josiele sena alves",
    "O.S Externa": ""
  },
  {
    "ID": "1073",
    "Data Cadastro": "2026-09-15",
    "Data Atendimento": "2026-09-22",
    "Hora": "09:30",
    "Placa": "SZC1E07",
    "Loja": "OFICINA",
    "Modelo": "OROCH PRO 16",
    "Contato": "COHAB",
    "Local/Oficina": "OFICINA MECANICA ARRAIS",
    "Problemas Relatado": "REVISÃO DE 50.000 KM, ALINHAMENTO E  BALANCEAMENTO, SUSPENSÃO ESTÁ SACUDINDO EMBAIXO ,O BICO INJETOR ESTÁ SUJO, O CARRO ESTÁ FALHANDO E DESLIGANDO AUTOMATICAMENTE, QUANDO PARA EM QUALQUER LUGAR",
    "Observação": "SUSANE - PRECISAR DE RESERVA",
    "Operador": "josiele sena alves",
    "O.S Externa": ""
  },
  {
    "ID": "1077",
    "Data Cadastro": "2026-09-16",
    "Data Atendimento": "2026-09-22",
    "Hora": "10:00",
    "Placa": "SZH1J06",
    "Loja": "OFICINA",
    "Modelo": "TORO VOLCANO AT9",
    "Contato": "SEASTER",
    "Local/Oficina": "OFICINA MECANICA ARRAIS",
    "Problemas Relatado": "REVISÃO DE KM: 60.000",
    "Observação": "DANIEL",
    "Operador": "josiele sena alves",
    "O.S Externa": ""
  },
  {
    "ID": "1084",
    "Data Cadastro": "2026-09-18",
    "Data Atendimento": "2026-09-21",
    "Hora": "08:00",
    "Placa": "RWX9F57",
    "Loja": "OFICINA",
    "Modelo": "RANGER XL CD4 2.2 C",
    "Contato": "FASEPA",
    "Local/Oficina": "OFICINA MECANICA ARRAIS",
    "Problemas Relatado": "REVISÃO DE KM, SUSPENSÃO, TROCA DE PNEUS E LAVAGEM",
    "Observação": "LAURO",
    "Operador": "josiele sena alves",
    "O.S Externa": ""
  },
  {
    "ID": "1072",
    "Data Cadastro": "2026-09-15",
    "Data Atendimento": "2026-09-21",
    "Hora": "08:30",
    "Placa": "TWF6F31",
    "Loja": "OFICINA",
    "Modelo": "HB20 10M COMFORT",
    "Contato": "SEAP",
    "Local/Oficina": "HYUNDAI UNIQUE",
    "Problemas Relatado": "REVISÃO 20.000 KM",
    "Observação": "RENATO",
    "Operador": "josiele sena alves",
    "O.S Externa": ""
  },
  {
    "ID": "1067",
    "Data Cadastro": "2026-09-14",
    "Data Atendimento": "2026-09-21",
    "Hora": "09:00",
    "Placa": "SZA6C95",
    "Loja": "OFICINA",
    "Modelo": "POLO TRACK",
    "Contato": "SEZEL",
    "Local/Oficina": "OFICINA MECANICA ARRAIS",
    "Problemas Relatado": "REVISÃO GERAL",
    "Observação": "ROSE",
    "Operador": "josiele sena alves",
    "O.S Externa": ""
  },
  {
    "ID": "1068",
    "Data Cadastro": "2026-09-14",
    "Data Atendimento": "2026-09-21",
    "Hora": "09:30",
    "Placa": "SZE8G54",
    "Loja": "OFICINA",
    "Modelo": "CRONOS DRIVE",
    "Contato": "SEASTER",
    "Local/Oficina": "GRUPO MONACO VEÍCULOS LTDA",
    "Problemas Relatado": "REVISÃO DE 40.000 KM",
    "Observação": "ALTAIR",
    "Operador": "josiele sena alves",
    "O.S Externa": ""
  },
  {
    "ID": "1070",
    "Data Cadastro": "2026-09-15",
    "Data Atendimento": "2026-09-21",
    "Hora": "10:00",
    "Placa": "SZO4C70",
    "Loja": "OFICINA",
    "Modelo": "HB20 10M COMFORT",
    "Contato": "SEGBEL",
    "Local/Oficina": "HYUNDAI UNIQUE",
    "Problemas Relatado": "REVISÃO DE 10.000 KM",
    "Observação": "HENRIQUE",
    "Operador": "josiele sena alves",
    "O.S Externa": ""
  },
  {
    "ID": "1076",
    "Data Cadastro": "2026-09-16",
    "Data Atendimento": "2026-09-21",
    "Hora": "10:30",
    "Placa": "QVX2A68",
    "Loja": "OFICINA",
    "Modelo": "GOL 1.0 MC 4",
    "Contato": "FUNPAPA",
    "Local/Oficina": "OFICINA MECANICA ARRAIS",
    "Problemas Relatado": "REVISÃO DE KM E AR CONDICIONADO NÃO FUNCIONA",
    "Observação": "MATHEUS",
    "Operador": "josiele sena alves",
    "O.S Externa": ""
  }
] as const;
