/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedHistoricosRouteImport } from './routes/_authenticated/historicos'
import { Route as AuthenticatedOficinaRouteImport } from './routes/_authenticated/oficina'
import { Route as AuthenticatedVeiculoPlateRouteImport } from './routes/_authenticated/veiculo.$plate'
import { Route as ApiPublicHooksSglocSyncRouteImport } from './routes/api/public/hooks/sgloc-sync'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHistoricosRoute = AuthenticatedHistoricosRouteImport.update({
  id: '/historicos',
  path: '/historicos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOficinaRoute = AuthenticatedOficinaRouteImport.update({
  id: '/oficina',
  path: '/oficina',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedVeiculoPlateRoute =
  AuthenticatedVeiculoPlateRouteImport.update({
    id: '/veiculo/$plate',
    path: '/veiculo/$plate',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicHooksSglocSyncRoute = ApiPublicHooksSglocSyncRouteImport.update({
  id: '/api/public/hooks/sgloc-sync',
  path: '/api/public/hooks/sgloc-sync',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/historicos': typeof AuthenticatedHistoricosRoute
  '/oficina': typeof AuthenticatedOficinaRoute
  '/veiculo/$plate': typeof AuthenticatedVeiculoPlateRoute
  '/api/public/hooks/sgloc-sync': typeof ApiPublicHooksSglocSyncRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/historicos': typeof AuthenticatedHistoricosRoute
  '/oficina': typeof AuthenticatedOficinaRoute
  '/': typeof AuthenticatedIndexRoute
  '/veiculo/$plate': typeof AuthenticatedVeiculoPlateRoute
  '/api/public/hooks/sgloc-sync': typeof ApiPublicHooksSglocSyncRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/historicos': typeof AuthenticatedHistoricosRoute
  '/_authenticated/oficina': typeof AuthenticatedOficinaRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/veiculo/$plate': typeof AuthenticatedVeiculoPlateRoute
  '/api/public/hooks/sgloc-sync': typeof ApiPublicHooksSglocSyncRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/historicos'
    | '/oficina'
    | '/veiculo/$plate'
    | '/api/public/hooks/sgloc-sync'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/historicos'
    | '/oficina'
    | '/'
    | '/veiculo/$plate'
    | '/api/public/hooks/sgloc-sync'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/historicos'
    | '/_authenticated/oficina'
    | '/_authenticated/'
    | '/_authenticated/veiculo/$plate'
    | '/api/public/hooks/sgloc-sync'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiPublicHooksSglocSyncRoute: typeof ApiPublicHooksSglocSyncRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/historicos': {
      id: '/_authenticated/historicos'
      path: '/historicos'
      fullPath: '/historicos'
      preLoaderRoute: typeof AuthenticatedHistoricosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/oficina': {
      id: '/_authenticated/oficina'
      path: '/oficina'
      fullPath: '/oficina'
      preLoaderRoute: typeof AuthenticatedOficinaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/veiculo/$plate': {
      id: '/_authenticated/veiculo/$plate'
      path: '/veiculo/$plate'
      fullPath: '/veiculo/$plate'
      preLoaderRoute: typeof AuthenticatedVeiculoPlateRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/hooks/sgloc-sync': {
      id: '/api/public/hooks/sgloc-sync'
      path: '/api/public/hooks/sgloc-sync'
      fullPath: '/api/public/hooks/sgloc-sync'
      preLoaderRoute: typeof ApiPublicHooksSglocSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedHistoricosRoute: typeof AuthenticatedHistoricosRoute
  AuthenticatedOficinaRoute: typeof AuthenticatedOficinaRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedVeiculoPlateRoute: typeof AuthenticatedVeiculoPlateRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedHistoricosRoute: AuthenticatedHistoricosRoute,
  AuthenticatedOficinaRoute: AuthenticatedOficinaRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedVeiculoPlateRoute: AuthenticatedVeiculoPlateRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiPublicHooksSglocSyncRoute: ApiPublicHooksSglocSyncRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
