CREATE TABLE public.user_roles (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid NOT NULL UNIQUE, role public.app_role NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
GRANT SELECT ON public.user_roles TO authenticated;
GRANT ALL ON public.user_roles TO service_role;
ALTER TABLE public.user_roles ENABLE ROW LEVEL SECURITY;
CREATE OR REPLACE FUNCTION public.has_role(_user_id uuid, _role public.app_role) RETURNS boolean LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public AS $$ SELECT EXISTS (SELECT 1 FROM public.user_roles WHERE user_id = _user_id AND role = _role) $$;
REVOKE EXECUTE ON FUNCTION public.has_role(uuid, public.app_role) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.has_role(uuid, public.app_role) TO authenticated;
CREATE POLICY "Own role readable" ON public.user_roles FOR SELECT TO authenticated USING (user_id = auth.uid());
INSERT INTO public.user_roles (user_id,role) SELECT id,role FROM public.profiles WHERE role IS NOT NULL ON CONFLICT (user_id) DO NOTHING;
CREATE OR REPLACE FUNCTION public.has_access(_user_id uuid) RETURNS boolean LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public AS $$ SELECT EXISTS (SELECT 1 FROM public.user_roles WHERE user_id = _user_id) $$;
REVOKE EXECUTE ON FUNCTION public.has_access(uuid) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.has_access(uuid) TO authenticated;
DROP POLICY "Masters delete" ON public.appointments;
CREATE POLICY "Masters delete" ON public.appointments FOR DELETE TO authenticated USING (public.has_role(auth.uid(), 'master'));
DROP POLICY "Masters create statuses" ON public.status_options;
DROP POLICY "Masters update statuses" ON public.status_options;
DROP POLICY "Masters remove statuses" ON public.status_options;
CREATE POLICY "Masters create statuses" ON public.status_options FOR INSERT TO authenticated WITH CHECK (public.has_role(auth.uid(), 'master'));
CREATE POLICY "Masters update statuses" ON public.status_options FOR UPDATE TO authenticated USING (public.has_role(auth.uid(), 'master')) WITH CHECK (public.has_role(auth.uid(), 'master'));
CREATE POLICY "Masters remove statuses" ON public.status_options FOR DELETE TO authenticated USING (public.has_role(auth.uid(), 'master'));
DROP POLICY "Masters create fields" ON public.custom_field_definitions;
DROP POLICY "Masters update fields" ON public.custom_field_definitions;
DROP POLICY "Masters remove fields" ON public.custom_field_definitions;
CREATE POLICY "Masters create fields" ON public.custom_field_definitions FOR INSERT TO authenticated WITH CHECK (public.has_role(auth.uid(), 'master'));
CREATE POLICY "Masters update fields" ON public.custom_field_definitions FOR UPDATE TO authenticated USING (public.has_role(auth.uid(), 'master')) WITH CHECK (public.has_role(auth.uid(), 'master'));
CREATE POLICY "Masters remove fields" ON public.custom_field_definitions FOR DELETE TO authenticated USING (public.has_role(auth.uid(), 'master'));
CREATE OR REPLACE FUNCTION public.enforce_appointment_edit_rules() RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE _role app_role; _business_changed boolean;
BEGIN
 IF auth.uid() IS NULL THEN RETURN NEW; END IF;
 SELECT role INTO _role FROM public.user_roles WHERE user_id = auth.uid();
 IF _role IS NULL THEN RAISE EXCEPTION 'Seu perfil não tem permissão para alterar agendamentos'; END IF;
 IF _role = 'master' THEN RETURN NEW; END IF;
 _business_changed := ROW(NEW.status,NEW.date,NEW.time,NEW.plate,NEW.store,NEW.model,NEW.contact,NEW.workshop,NEW.issue,NEW.note,NEW.operator,NEW.external_order,NEW.original_deadline,NEW.current_deadline,NEW.priority_urgent,NEW.rework_of,NEW.rework_reason,NEW.sgloc_reference,NEW.registered_at,NEW.sheet_id,NEW.created_by,NEW.creator_edits_used,NEW.manager_edit_used,NEW.custom_fields) IS DISTINCT FROM ROW(OLD.status,OLD.date,OLD.time,OLD.plate,OLD.store,OLD.model,OLD.contact,OLD.workshop,OLD.issue,OLD.note,OLD.operator,OLD.external_order,OLD.original_deadline,OLD.current_deadline,OLD.priority_urgent,OLD.rework_of,OLD.rework_reason,OLD.sgloc_reference,OLD.registered_at,OLD.sheet_id,OLD.created_by,OLD.creator_edits_used,OLD.manager_edit_used,OLD.custom_fields);
 IF _role = 'gerente' THEN
  IF NOT _business_changed AND NEW.creator_edits_allowed = OLD.creator_edits_allowed + 1 THEN RETURN NEW; END IF;
  IF OLD.manager_edit_used THEN RAISE EXCEPTION 'Limite de edição do gerente já foi usado neste agendamento'; END IF;
  NEW.creator_edits_allowed := OLD.creator_edits_allowed; NEW.creator_edits_used := OLD.creator_edits_used; NEW.manager_edit_used := true; RETURN NEW;
 END IF;
 IF OLD.creator_edits_used >= OLD.creator_edits_allowed THEN RAISE EXCEPTION 'Limite de edições deste agendamento já foi atingido'; END IF;
 NEW.creator_edits_allowed := OLD.creator_edits_allowed; NEW.manager_edit_used := OLD.manager_edit_used; NEW.creator_edits_used := OLD.creator_edits_used + 1; RETURN NEW;
END $$;
REVOKE EXECUTE ON FUNCTION public.enforce_appointment_edit_rules() FROM PUBLIC, anon, authenticated;
ALTER TABLE public.profiles DROP COLUMN role;